# Site settings
title: Vishal's Web
description: "Web of Vishal Kukreja"  # used in site head

# footer details. Deleting the value would remove it from footer.
github_username:  vishalkukreja
facebook_username:  vishal.a.kukreja
email: vishalkukreja90@gmail.com
stackoverflow_username: 2803335/vishal-kukreja
twitter_username : vishalkukreja
linkedin_username : kukrejavishal
copyright_name: Vishal Kukreja
rss : true

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
